name: Deploy to Production

on:
    push:
        branches: [main]

jobs:
    # Bump version using semantic-release
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'
            - run: npm install
            - name: Semantic Release
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Build the final app
    build:
        # Add a dependency to the build job
        needs: release
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'
            - run: npm install
            - run: npm run build
            - name: Upload artifact to enable deployment
              uses: actions/upload-artifact@v3
              with:
                  name: production-files
                  path: ./dist

    # Deploy the app
    deploy:
        # Add a dependency to the build job
        needs: build
        # Specify runner + deployment step
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: production-files
                  path: ./dist
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.CI_CD_TOKEN }}
                  publish_dir: ./dist
